### ISSUE TITLE
Support for partial printing

### ISSUE THREAD

**Issue by ArcCha** [KSIUJ/gutenberg#5]
Support for partial printing would be very much appreciated. I mean, user should have an option to select which pages he wishes to print, like in standard printer dialog using:

- page number enumeration (eg. `1, 2, 8, 12`)
- page number ranges (eg. `1-2, 3-12, 18')

**Comment by danielskowronski** [comment]
I guess we need to add gs options like `-dFirstPage` and `-dLastPage` support

**Comment by m4tx** [comment]
The support was added in 1198b52f57d84348e0aee843bda65e5d1b743540. Requires testing before closing the issue though.
